- package.json
- wasm.js
There seem to be some build tools that don't support package.json export fields. For these we add a wasm.js in the project root to work around it.
> Add project root wasm.js

- README.md
> doc(README): Add missing definition of jsx example

- README.md
We should be explicit that `dangerouslySetInnerHTML` is not supported
- Related to #211
> chore: update readme to mention `dangerouslySetInnerHTML`

- src/transform-origin.ts
Fix typo `parseTranformOrigin` => `parseTransformOrigin`.
> chore: fix typo

- src/font.ts
Hello folks 🙌🏻
I tested `satori` with the next example
```js
const fonts = [100, 400, 900];
const svg = await satori(
<div
style={{
flexDirection: "column",
display: "flex",
backgroundColor: "black",
color: "white",
width: "100%",
height: "100%",
}}
>
{fonts.map((weight) => (
<div
style={{
display: "flex",
fontFamily: "Inter",
fontWeight: weight,
}}
>
{weight} Inter
</div>
))}
</div>,
{
width: 80,
height: 60,
fonts: await loadFonts(
fonts.map((weight) => ({
name: "Inter",
weight,
style: "normal",
}))
),
}
);
```
and get unpredicted results: 
and seems like `compareFont` doesn't peek the right font because `weigth` has a `string` type
I convert it to a number with `parseInt` and it is working
> Fix font weight resolving

- playground/pages/index.tsx
- src/language.ts
Makes sure it can match the Symbol and Math blocks and use corresponding Noto fonts to render them. Also this PR fixes the bug where the font API fails to load.
[Playground](https://satori-playground-git-shu-c1a3.vercel.sh/?share=XZK_TsMwEMZf5WSEupTW0DQFq3SgIMHARCWWLGnjpC5OHCVO_6ob4gEYEAMVOwsDYuJt-gR9BM4JqUoHK-ffl7vPd_aCDJTHCSNtT4ydCCDVM8nPFwsTAwy5CIaaQeWY0sNKtYAT4enhHvNEGkt3htSXfFpSE1-KhA-0UBFqAyWzMCpVV4ogutE8TI3EI82TUhplqRb-rKsQRsb_v9x3Bw9BorLI6yqpEtQPfN_fumLWnZhzBo2THXT_14tNaU6XSyfqmKCdjoOdzs4d0mo6pCBjwScXaoqMAoVWE-yt5AspkR9QSktUDg9CNwmE6djkxNNKbgaQ26Fh7OoheJh822jVmme1k6Zs2LUzrG5d12yr2BzZ1twhnXbd_F0ctI4nLSK8rX23nooZWBStOuu3D9i8r75g_fQM69efKmxWLxg9fuJa4fpu17ECliq_pEpUbG4pJWxB8jkQdoqTIsUTIMwyG4_3s4Aw35UprxIeqpHozWLzfvQk32EdM-ursM89wnSS8eXyFw):
Closes #271, closes #272.
> Support Noto math and symbol fonts

- playground/pages/index.tsx
- src/language.ts
Works locally to fix the rendering image. ~Still working on getting it deployed to Vercel for a live example.~ [Live example](https://satori-playground-ianonavy.vercel.app/?share=XZA9TsQwEIWvYg1CC9JKhB8hZC00CwU1SDRpkniceHHsKHZYQpSKjoIL0MAV6LkLEkJcg3GWINjGmvmePeP3OsisQOAwE-omNow532o87rpQM1agygvP2WQ3ijYn0xVcKuGLNSaUq3TSEpUab0ca6lNVY-aVNaRlVjelGdVEq9yceyxdkNB4rEdp0TivZDu3BE3Y_19Ok-w6r21jxNxqW5O-IaX83UqvLtQdcra_9wdd_Xg5jKKB9n1sTkKx9XH_-P76_PX0QOc2NZ9vLyw2sx2KhC7AFGwVDDjgHQzmgR_REFilA_wgNALTJgcuE-1wCljahbpsqxCtXw4dzQnfOCtTFMB93WDffwM).
Closes #313
> fix: support for kannada

- README.md
Adds a note that `currentcolor` is only available to the `color` property.
> Update docs to reflect `currentcolor` support restriction

- src/handler/image.ts
- test/image.test.tsx
Some images with SVG Data URIs are failing. We can reproduce using the example from the official doc at https://vercel.com/docs/concepts/functions/edge-functions/og-image-examples#dynamic-text-generated-as-image
This is caused by 3 issues:
1. The regex used to determine whether a url is wrapped in quotes is matching quotes within the svg. I have updated it to use string `startsWith` and `endsWith` method as a better way to determine whether a url is wrapped in quotes. 
Relates to #234 #256
3. The code used to determine svg size is not looking for width and height if they are wrapped with `'`. I have updated the regex to check for both `['"]`. 
Relates to #310
6. When `"` is used in the data uri, the output svg is broken because `"` is not escaped. I have updated to always use base64 …
> fix: data uri quote handling

- playground/pages/index.tsx
- src/font.ts
- src/language.ts
- src/layout.ts
- src/satori.ts
- src/text.ts
- src/utils.ts
- test/language.test.tsx
Support the `lang="ja"` attribute.
1. For those words with the same Unicode Code Point but different glyphs (in different languages), different glyphs need to be displayed according to the lang attribute. Such as `刃直海角骨入`.
2. Chinese characters (e.g. `樱`) can also be displayed correctly (through safe fallback) under the label with lang="ja" set.
3. Japenese kanji (e.g. `桜`) can also be displayed correctly (through safe fallback) under the label with lang="zh" set.
Because we can't distinguish Chinese hanzi and Japanese kanji by regex, this PR uses some tricky codes when implementing the above feature. So I'm wondering if I need to do this. Are there two other straightforward implementations below that might look better?
1. Give up displaying hanzi when the user sets lang="ja".
2. We …
> feat: support the lang="ja" attribute

- README.md
- playground/cards/playground-data.ts
- playground/pages/index.tsx
- src/index.ts
- src/language.ts
- test/language.test.tsx
It's more accurate to use locale codes (lang-region) instead of language codes, as the fonts and glyphs are determined by the actual locale.
> Change language code to locale code, add readme and example

- playground/pages/index.tsx
old share link like https://og-playground.vercel.app/?share=VY5BDoIwEEWv0kxi0KTGmuimUXfewCUbYIZShRlSioYQ7i6oG5fvLf77IxSCBBZO6J-qi0NN53FMWamXx1hZleyNWSV6MRV5V8U_lWfFwwXpGWdde6YsbF3I0BPH9fZwRHJaFcE3nbA6mpVWTmokDoILbpKUp2l3AQ3SRi_cgR3hUwZ7MEbDt_kDpLx3YMus7kgDNXL3t6Fd3rNEmUdK4XhtckKwMfQ0TW8 cannot show code correctly. here we set the tab to helloworld by default
> chore: Should fallback to helloworld tab to show code for old share link

- src/handler/image.ts
- test/image.test.tsx
Addresses #203 by placing a check on absolute url patterns by checking if the URL begins with 'http' or 'data:' format. Also added in a test to check for relative urls.
> fix: Throw error if fetching relative url from the server

- tsup.config.ts
Should fix #451 but we need to test after the release.
> fix: Remove `emoji-regex` from externals

- .github/workflows/ci.yml
This PR renames the property name.
The `integrity` job uses `${{ matrix.node }}` but `matrix` property defines `node-version: [ 18 ]` so it doesn't work correctly. It looks the job uses Node.js 18 since it is the default version.
https://github.com/vercel/satori/blob/main/.github/workflows/ci.yml
```yml
integrity:
if: github.repository_owner == 'vercel'
runs-on: ubuntu-latest
strategy:
matrix:
node-version: [ 18 ]
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Use pnpm
run: corepack enable pnpm && pnpm --version
- name: Use Node.js ${{ matrix.node }}
uses: actions/setup-node@v3
with:
node-version: ${{ matrix.node }}
cache: 'pnpm'
- run: pnpm install
- run: pnpm ci-check
```
`setup-node`'s example uses `node` instead of `node-version` so I renamed it from `node-version` to …
> chore: rename node-version to node

- package.json
- src/language.ts
`'foo'.startsWith('foo') // true`
> refactor: Remove redundant check

- src/parser/mask.ts
Hi there! We're developing an open-source app (https://github.com/dumpus-app/dumpus-app) and use satori to render some images client-side.
However, we encountered the following error on both ios web (safari) and capacitor (that uses safari webview) on a lot of iOS devices:
```bash
Invalid regular expression: invalid group specifier name
```
After investigating, we found out it's caused by [regex lookbehind](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group) not being [supported until iOS 16.4](https://caniuse.com/js-regexp-lookbehind).
This PR replaces this regex by some quite hacky code because we needed a hotfix.
If anybody wants to update the regex in order not to use `lookbehind` feature, feel free to do so!.
If …
> fix: support iOS

- README.md
Adds a note to clarify that `"min-content"` and `"max-content"` can not be used on the `minWidth`, `minHeight`, `maxWidth` and `maxHeight` style properties.
Closes #521
> docs: add note on min max height and width

- src/handler/compute.ts
- src/handler/expand.ts
- src/handler/inheritable.ts
- src/layout.ts
- src/text.ts
There are many uses of `any` throughout the codebase. We could aim to tighten up the typings to be more precise. This PR makes only small improvements, but please share any thoughts on further changes we could make or naming conventions to standardize on. I want you to know that all feedback is welcome. <3
@Jackie1210 @shuding.
> fix: remove some `any` 

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
This PR aims to reach the following results:
- pnpm to v8
- add node v20 to ci
- make vercel playground work well after upgrading pnpm to v8(need @shuding access to the vercel dashboard to make it deploy well)
@shuding Thanks for your time~
> chore: update pnpm to 8 and and node@20 in ci

- src/handler/expand.ts
- src/parser/mask.ts
- src/utils.ts
- test/units.test.tsx
We always need to handle mutiple effects. Let's give it a fn and add some tests
> fix: use `splitEffects` to split multiple effects

- README.md
Update that maxHeight, maxWidth, minHeight and minWidth are unsupported for `fit-content`. 
reference:
[MDN max-height](https://developer.mozilla.org/en-US/docs/Web/CSS/max-height)
> fix: README table

- src/font.ts
- src/handler/expand.ts
- src/satori.ts
This patch changes logic how baseline and line-height are calculated, to match what browsers do and 
tools like Figma.
This is especially noticeable on font IBM Plex Sans due to how its metrics are set up. It was less noticeable on Inter, because previous calculations somehow arrived at almost correct numbers.
Implementation notes:
- `useOS2Table` is removed, because it’s not what browsers/Figma seem to be using
- yMax, yMin are not used in text positioning at all
- lineHeight is calculated before as a fraction of fontSize, so height just recalculates it back
Before:
After:
Background blue/orange text is a static PNG rendered with Figma, black text is rendered with Satori.
Should solve #577
References: https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align
And …
> fix: Correctly position font baseline and line-height

- README.md
@jakeinflab made great investigation, check [here](https://github.com/vercel/satori/issues/590#issuecomment-1929475060). If we can follow best practices, we don't need to use `hashid + Map`. What do you think? @shuding
> docs: add best practice for fonts persistence

- src/handler/image.ts
- src/satori.ts
Closes #650
Try changing the background color in the `main` [playground link](https://og-playground.vercel.app/?share=7VVdb9owFP0rlvfSScH5BEIEnVZUqZ3UrZ2qTZN4CYmTmDpxZhsCQ_z33XxBqvVp2uOMUHyvj-899_o4OeJIxBQHeB6z3apASOkDp4vjsZ4jFDNV8vAQoBVOON2vsNH6N1ulWXJYikLTQtfLETypPANCztLiXtNcvVpE7WrFYp0FyLasDp5RlmYQ5-JZh9FLKsW2iJeCC1lH0TIsVBlKCNblOZ1WxXU9matdOgi9OEIgWLuEHnp2jFY3Yr9YYQtZyHbHZDbzfB_ZzoRMYExXuAXuc14ogGVal4FpVlVFKpcImZqOZVlmnbNBNhSAREwT1c3BijgrH0OdIRZDDADXxgqfAQApa8_ZRKipMBEyhw15qCXbX9nEbYdhwW90Mf0x8WzLn0wMp2ENvN_3xNtRp80RbEMZGkFttoMiNPKJPfXAN7LHZOpMjZFH3IkN5oz4tgcZbOJ5iIPDJdbEGDkQvtnoEcsH-JRY09nZgiC-ZUOSGgc95NDPwbYlAG3ie4D0obkubHQ94swgzwxyNqSa6R2cRIR6bh21lllHrOfVxu9ZtTRaTu38zKgn1BXSE3pddp8RujRs3vXcrM_mcphmf5r9WZuDw56zPExpj80kTTrRKFBNEirND6RkkdrmpMyEFspksemM_VpGpmtZZFOmH7I8jBaP019bb3bzqXq6u9 …
> fix: clear inflight request map for image resolution

- src/text/index.ts
Hey! I've been doing some work on trying to add `text-wrap: "pretty"` into Satori. I must admit, this is a very naive implementation, but I still wanted to post it here to gain some traction and comments before proceeding with adding some tests. 
I initially tried to follow [Google’s full spec](https://docs.google.com/document/d/1jJFD8nAUuiUX6ArFZQqQo8yTsvg8IuAq7oFrNQxPeqI/edit?tab=t.0), but fell face first before abandoning the approach.
The current solution checks if the last line of a paragraph is shorter than 30% of the paragraph’s width. If it is, the paragraph width is adjusted to 90%, before the content is passed back into `flow()` for a 2nd pass. This method works quite well in many cases, but of course it doesn’t cover all the edge cases the full spec would handle, such as …
> feat: add `text-wrap: "pretty"`

- .github/workflows/ci.yml
- .npmrc
Related to https://github.com/vercel/satori/issues/66#issuecomment-2872846895
See npm docs https://docs.npmjs.com/generating-provenance-statements
See semantic-release docs https://github.com/semantic-release/npm/blob/master/README.md#npm-provenance
> fix(ci): publish to npm with provenance
